# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

transformers:
  - |-
    apiVersion: fn.kpt.dev/v1alpha1
    kind: RenderHelmChart
    metadata:
      name: demo
      annotations:
        config.kubernetes.io/function: |
          exec:
            path: render-helm-chart
    helmCharts:
    - chartArgs:
        name: hello-chart
        repo: oci://us-central1-docker.pkg.dev/xinn-gke-dev/helm-oci-1
        registry: https://us-central1-docker.pkg.dev
    - chartArgs:
        name: hello-chart-2
        repo: oci://us-west1-docker.pkg.dev/xinn-gke-dev/quickstart-helm-repo
        registry: https://us-west1-docker.pkg.dev

